### ISSUE TITLE
question: Will `type=semver` work if I tag releases the GitHub way (using Releases feature)?

### ISSUE THREAD

**Issue by AndreiJirohHaliliDev2006** [docker/metadata-action#103]
Just an question. Can I use this action when triggered by `release.published` (or `release.released` for stable releases and `release.prereleased` for technical preview-like releases) or do I need to do `git tag` first?

Thanks in advance!

**Comment by crazy-max** [comment]
@AndreiJirohHaliliDev2006 

> Can I use this action when triggered by `release.published` (or `release.released` for stable releases and `release.prereleased` 

Yes. The git ref will be `refs/tags/<name>` which will be used by `type=semver`.

>  or do I need to do `git tag` first?

[GitHub Releases](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/about-releases) are based on Git tags.

**Comment by AndreiJirohHaliliDev2006** [comment]
Thanks, @crazy-max.
