### ISSUE TITLE
[Question] Latest tag when push to master

### ISSUE THREAD

**Issue by robsontenorio** [docker/metadata-action#112]
Hi!

A dummy question: how to generate `latest` tag when pushing to master? Currently it generates the `master` tag.

**Comment by robsontenorio** [comment]
Got it. Is there any better way?

```yaml
tags: |
            type=ref,event=tag
            type=raw,enable=${{ github.ref == 'refs/heads/master' }},value=latest
```

**Comment by crazy-max** [comment]
@robsontenorio 

> Got it. Is there any better way?

It will work but latest tag will also be generated on Git tag event (`type=ref,event=tag`). If you ONLY want latest tag when pushed to master you should set the latest flavor instead:

```yaml
flavor: |
  latest=${{ github.ref == 'refs/heads/master' }}
```
