### ISSUE TITLE
Description and license label source?

### ISSUE THREAD

**Issue by ksurl** [docker/metadata-action#113]
Where does it pull from to fill the oci labels for description and license? Mine are blank though I do not have a license.md file in my repo (my 1st guess for license?).

**Comment by crazy-max** [comment]
@ksurl 

> Where does it pull from to fill the oci labels for description and license

These values are extracted from the GitHub API:

https://github.com/docker/metadata-action/blob/f6efe56d565add159ad605568120f5b22712a870/src/meta.ts#L366-L373

For `description` and `license` we use [`/repos/{owner}/{repo}`](https://docs.github.com/en/rest/reference/repos#get-a-repository). 

To add a license to your repo see https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository.

To change the repo description: https://stackoverflow.com/a/62767178/514571

You can also overwrite labels if you want: https://github.com/docker/metadata-action#overwrite-labels
