### ISSUE TITLE
Make input variable names POSIX-compliant

### ISSUE THREAD

**Issue by gperdomor** [docker/metadata-action#114]
### Troubleshooting

Environment variables provided to the docker build push action through with that contain a '-' are not easily accessible, and are moreover not POSIX-compliant.

At the end, something like `sep-tags ` is translated to `INPUT_SEP-TAGS` by the actions toolkit. Let's say that we need to set that environment variable depending of the output of other command using `export INPUT_SEP-TAGS=\n`, we can't.

#### Expected behaviour

Maybe is a good idea to switch to a underscore variable names like `sep_tags`, `sep_labels` and make all input names POSIX-compliant...

This is related to https://github.com/docker/build-push-action/issues/404

**Comment by crazy-max** [comment]
@gperdomor 

> Environment variables provided to the docker build push action through with that contain a '-' are not easily accessible, and are moreover not POSIX-compliant.
> 
> At the end, something like `sep-tags ` is translated to `INPUT_SEP-TAGS` by the actions toolkit. Let's say that we need to set that environment variable depending of the output of other command using `export INPUT_SEP-TAGS=\n`, we can't.

Maybe for a [Container action](https://github.com/actions/container-toolkit-action) but we use a [Typescript action](https://github.com/actions/typescript-action) here so I don't think this is related.

Closing but feel free to let us know if there is any kind of limitation with our action linked to this with a repro. Thanks.
