### ISSUE TITLE
When using type=raw,value=myName-{{branch}}-{{tag}}-{{date 'YYYYMMDD'}}-{{sha}}, tag is not picked up

### ISSUE THREAD

**Issue by janderssonse** [docker/metadata-action#127]
### Behaviour

When using type=raw,value=myName-{{branch}}-{{tag}}-{{date 'YYYYMMDD'}}-{{sha}}, tag is not picked up, even though tags exist.

#### Steps to reproduce this issue

See the workflow at 
https://raw.githubusercontent.com/janderssonse/homebrew-avtools/main/.github/workflows/publish.yaml

Tags exist.

The output is 
![bild](https://user-images.githubusercontent.com/37870813/131075054-4f8297c9-db5f-42f1-a036-a069a24d4e0a.png)

ie filling in the other fields but missing the tag.

#### Expected behaviour

The tag should also be filled, as there exists tags

#### Actual behaviour

The tag is empty

### Configuration

https://github.com/janderssonse/homebrew-avtools
https://raw.githubusercontent.com/janderssonse/homebrew-avtools/main/.github/workflows/publish.yaml

**Comment by crazy-max** [comment]
@janderssonse Looks good to me in your last build: https://github.com/janderssonse/homebrew-avtools/runs/3489046168?check_suite_focus=true#step:6:996

![image](https://user-images.githubusercontent.com/1951866/131746114-2e6c2402-0135-43e2-86d4-d83ac148414d.png)

**Comment by janderssonse** [comment]
I think you closed it to early?? The picture you show from the build actually shows the missing tag value
![131746114-2e6c2402-0135-43e2-86d4-d83ac148414d](https://user-images.githubusercontent.com/37870813/131757216-ddffe0a5-e9ac-43c1-af11-8a908a402451.png)

Format given was : value=myName-{{branch}}-{{tag}}-{{date 'YYYYMMDD'}}-{{sha}}, tag is not picked 

The {{tag}} does not shows, see underlined red in in your build picture. Tags exists in the project.

**Comment by crazy-max** [comment]
@janderssonse Tag is only populated if the Git ref that triggered the workflow is a tag (eg. `refs/tags/xxx`). In your case for https://github.com/janderssonse/homebrew-avtools/runs/3489046168?check_suite_focus=true the ref is [`refs/heads/main`](https://github.com/janderssonse/homebrew-avtools/runs/3489046168?check_suite_focus=true#step:5:22).

**Comment by janderssonse** [comment]
Aha, the explains it, I'll add a condition then, thanks
