### ISSUE TITLE
Add both version tag and branch name tag

### ISSUE THREAD

**Issue by max-arnold** [docker/metadata-action#137]
I have the following configuration:

```
            type=raw,value={{branch}}
            type=sha
            type=semver,pattern={{version}}
```

But when I push just a tag to the main branch, the container is tagged only with `latest`, `1.0.0` and `sha` tags, but not with the branch name.

Is it possible to always have a branch name tag in addition to version tag? The goal is to be able to refer either to a specific version tag or the latest container build in each branch.

**Comment by gaby** [comment]
@max-arnold Did you try adding these:

```
type=ref,event=branch
```

**Comment by max-arnold** [comment]
Yes, that is what I tried initially. The problem is that when you push just a tag, the ref event will be also the tag (not branch)
