### ISSUE TITLE
Create latest tag for commits on a specific branch

### ISSUE THREAD

**Issue by pganster** [docker/metadata-action#138]
As far as I can see there are two cases in which the `latest` tag is applied:

1. `latest=auto`, for commits that have a git tag 
2. `latest=true`, for every single commit on any branch

Another option, that would be useful, is where the latest tag is pushed on every single commit on a selected branch. E.g. `latest=branch,main`, like it's done with `type=edge,branch=main`.

**Comment by crazy-max** [comment]
@pganster https://github.com/docker/metadata-action/issues/112#issuecomment-877859644 should do it.
