### ISSUE TITLE
Confused about the usage of 'raw'

### ISSUE THREAD

**Issue by LinuxSuRen** [docker/metadata-action#154]
I feel pretty confused about the usage of `raw`. According to the explanation, users always get the actual tag name. But it has different results for a release and pre-release.

I'm wondering if it's possible to let it have the same behavior.

```
* `raw` ; the actual tag

| Git tag            | Pattern                                                  | Output               |
|--------------------|----------------------------------------------------------|----------------------|
| `v1.2.3`           | `{{raw}}`                                                | `v1.2.3`             |
| `v2.0.8-beta.67`   | `{{raw}}`                                                | `2.0.8-beta.67`*     |
```

I already read the following explanation. But I cannot understand why a pre-release version should not have the prefix `v`.

```
> *Pre-release (rc, beta, alpha) will only extend `{{version}}` as tag because they are updated frequently,
> and contain many breaking changes that are (by the author's design) not yet fit for public consumption.
```

**Comment by crazy-max** [comment]
@LinuxSuRen Good point, raw should always return the actual tag, even for a pre-release. Will fix that.

**Comment by crazy-max** [comment]
@LinuxSuRen #155 should fix this issue. You can try with `crazy-max/docker-metadata-action@prerelease-raw`.

**Comment by LinuxSuRen** [comment]
@crazy-max I'm not sure if I use it correctly. But it seems not work well.

![image](https://user-images.githubusercontent.com/1450685/144868108-956b82fb-82f5-446e-9362-8cf67896e82b.png)

## Refs
* https://github.com/linuxsuren-bot/test/runs/4431889983?check_suite_focus=true
* https://github.com/linuxsuren-bot/test/blob/47000542bc3f68c4b38ad7608a856c961cae84ac/.github/workflows/build.yaml#L28

**Comment by crazy-max** [comment]
@LinuxSuRen Looks like a typo: `type=semver,pattern=pattern={{raw}}` > `type=semver,pattern={{raw}}`

**Comment by LinuxSuRen** [comment]
My bad. It works well. Thanks for your quick fixing. Great job!
