### ISSUE TITLE
Add option to enable/disable images

### ISSUE THREAD

**Issue by lucacome** [docker/metadata-action#159]
This is a feature request. Would it be possible to add options to images, similar to tags?

example:
```
images: |
	name=myapp/foo,enable=${{ startsWith(github.ref, 'refs/tags') }}
	name=other/registry,enable=${{ github.event_name == 'pull_request' }}
```

or even:
```
images: |
	name=myapp/foo,event=tag
	name=other/registry,event=pr
```

Thanks!

**Comment by crazy-max** [comment]
@lucacome Yes in the first version of this action the images were merged to the tags input but the config was too verbose. An `enable` type for images sgtm though.

**Comment by Xerkus** [comment]
Since this is GHA action, I think `if` with conditional would be more consistent

**Comment by crazy-max** [comment]
@lucacome I have started smth in #193 if you want to take a look.

Can be tested with `crazy-max/docker-metadata-action@images-opts`. Docs: https://github.com/crazy-max/docker-metadata-action/tree/images-opts#images-input
