### ISSUE TITLE
Clarification regarding pushing the latest tag

### ISSUE THREAD

**Issue by GoliathLabs** [docker/metadata-action#162]
Hello!
we are currently using this github action and I would like to thank everyone involved for your work!
However, there might be a need for clarification in the readme regarding pushing the latest tag. Currently it's written a bit confusingly, leading to conversations like this: https://github.com/freifunkMUC/wg-access-server/pull/70#issuecomment-1021594476

Is there perhaps a better way to clarify this so we know if we have the action configured correctly in our workflow?

Thanks again for your work!

**Comment by crazy-max** [comment]
Hi @GoliathLabs, I think this section https://github.com/docker/metadata-action#latest-tag is clear enough? As explained, `latest` tag will be generated for `type=ref,event=tag`, `type=semver` and `type=match` when [`latest=auto` as `flavor` (default)](https://github.com/docker/metadata-action#flavor-input).

**Comment by DasSkelett** [comment]
So to summarize: with default settings, the image will only be tagged with `latest` if the build is triggered by a Git tag push, right?

I think a sentence like this would be useful in the "latest tab" section of the README, so you don't have to hunt down and decrypt information about all these types and when each of them is triggered.

**Comment by crazy-max** [comment]
> So to summarize: with default settings, the image will only be tagged with `latest` if the build is triggered by a Git tag push, right?

Not just on git tag. You can specify a custom value with `value=`.

**Comment by DasSkelett** [comment]
> You can specify a [custom value with `value=`](https://github.com/docker/metadata-action#typesemver).

But that wouldn't be default settings then, right?

**Comment by felipecrs** [comment]
@crazy-max is there any difference between:

```yaml
tags: |
  type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
```

And

```yaml
flavor: |
  latest=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
```

?

If there isn't one, why the latter isn't the one used in the README example?
