### ISSUE TITLE
Missing latest tag on type=semver

### ISSUE THREAD

**Issue by jonathangreen** [docker/metadata-action#163]
### Behaviour

I'm not seeing latest tag on my images, when I expect I should be seeing them. Its possible I'm just not understanding how `flavor: latest=auto` is supposed to work, but I thought that I would see the latest tag on any images that get `semver` tags.

Thank you for the help 🙏🏻 This is a fantastically useful action, I really appreciate you building it and putting it out there.

#### Steps to reproduce this issue

1. Using the config 
    ```
          uses: docker/metadata-action@v3
          with:
            images: ghcr.io/${{ github.repository_owner }}/${{ inputs.image }}
            tags: |
              type=semver,pattern={{major}}.{{minor}},priority=10
              type=semver,pattern={{version}},priority=20
              type=ref,event=branch,priority=30
              type=sha,priority=40
    ```
3. Run workflow on a release with tag `v1.0.0`

#### Expected behaviour

I expect to see the image tagged with:
`1.0`, `1.0.0`, `sha-7c07a4a`, `latest`

#### Actual behaviour

I don't see the latest tag. I get an image tagged with: 
`1.0`, `1.0.0`, `sha-7c07a4a`

### Configuration

* Repository URL: https://github.com/jonathangreen/circulation
* Build URL: https://github.com/jonathangreen/circulation/runs/4956566177
* Built package URL: https://github.com/jonathangreen/circulation/pkgs/container/circ-scripts
* Workflow: https://github.com/jonathangreen/circulation/blob/main/.github/actions/docker-push/action.yml

### Logs

[logs_220.zip](https://github.com/docker/metadata-action/files/7945354/logs_220.zip)
[10_Push circ-scripts.txt](https://github.com/docker/metadata-action/files/7945363/10_Push.circ-scripts.txt)

To see the specific behaviour take a look in the `Push circ-scripts` step.

**Comment by crazy-max** [comment]
@jonathangreen That's because you changed the default priority of the types:

```yaml
        tags: |
          type=semver,pattern={{major}}.{{minor}},priority=10
          type=semver,pattern={{version}},priority=20
          type=ref,event=branch,priority=30
          type=sha,priority=40
```

Here `type=sha` will be top priority and set as main version. Therefore latest tag will be skipped because `sha` type is not part of the flavor `latest` automation. I suggest to remove the priorities as I don't think you need them anyway:

```yaml
        tags: |
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{version}}
          type=ref,event=branch
          type=sha
```

**Comment by jonathangreen** [comment]
Ahh! I see. Thank you very much for the help. I didn't realize flavor only gets applied to the highest priority tag. 

Do you mind elaborating on why you changed the order? Does the order of the tags set the priority if no other priority is given?

**Comment by crazy-max** [comment]
> Do you mind elaborating on why you changed the order? Does the order of the tags set the priority if no other priority is given?

Each type has a default priority: https://github.com/docker/metadata-action/blob/2cad85de2462ab92a22ff973a347fb25c91d6082/src/tag.ts#L43-L52

So for:

```yaml
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=ref,event=branch
          type=sha
```

We have the following priorities:

* `900`
* `900`
* `600`
* `100`

I placed `type=semver,pattern={{version}}` first so it will marked as the "main" version.

As an example, if you push the git tag `v1.2.3`, then `1.2.3` will be the "main" version. This main version is used for [OCI Image Format Specification](https://github.com/opencontainers/image-spec/blob/master/annotations.md) labels and also the [generated bake definition](https://github.com/docker/metadata-action#bake-definition):

```json
{
  "target": {
    "docker-metadata-action": {
      "tags": [
        "name/app:1.2.3",
        "name/app:1.2",
        "name/app:sha-90dd603",
        "name/app:latest"
      ],
      "labels": {
        "org.opencontainers.image.title": "Hello-World",
        "org.opencontainers.image.description": "This your first repo!",
        "org.opencontainers.image.url": "https://github.com/octocat/Hello-World",
        "org.opencontainers.image.source": "https://github.com/octocat/Hello-World",
        "org.opencontainers.image.version": "1.2.3",
        "org.opencontainers.image.created": "2020-01-10T00:30:00.000Z",
        "org.opencontainers.image.revision": "90dd6032fac8bda1b6c4436a2e65de27961ed071",
        "org.opencontainers.image.licenses": "MIT"
      },
      "args": {
        "DOCKER_META_IMAGES": "name/app",
        "DOCKER_META_VERSION": "1.2.3"
      }
    }
  }
}
```
