### ISSUE TITLE
Specify default flavor

### ISSUE THREAD

**Issue by MarcelCoding** [docker/metadata-action#174]
### Behaviour

In the v1 there was a PR with a nice flavor system, unfortunately you didn't used it. Because of that, I forked your action and merged this PR myself. I saw that you now have a flavor system and tried to use it but I just don't get it. I have a build matrix where every combination is a flavor and don't get how to correctly specify the default flavor. The sam for `edge`.

#### Steps to reproduce this issue

https://github.com/MarcelCoding/java-backend/blob/8c4bb556108a1034d66d58a49f545721b12784d7/.github/workflows/ci.yaml#L100-L115

#### Expected behavior

```
ghcr.io/marcelcoding/cryptic-auth:1.0.0-jvm
ghcr.io/marcelcoding/cryptic-auth:1.0-jvm
ghcr.io/marcelcoding/cryptic-auth:1-jvm
ghcr.io/marcelcoding/cryptic-auth:jvm
ghcr.io/marcelcoding/cryptic-auth:1.0.0
ghcr.io/marcelcoding/cryptic-auth:1.0
ghcr.io/marcelcoding/cryptic-auth:1
ghcr.io/marcelcoding/cryptic-auth:latest

```

#### Actual behaviour

![image](https://user-images.githubusercontent.com/34819524/159051748-cb0f882a-c519-4fba-a005-105c07daf0f4.png)

### Configuration

* Repository URL (if public): https://github.com/MarcelCoding/java-backend/tree/8c4bb556108a1034d66d58a49f545721b12784d7
* Build URL (if public): 
    * tag: https://github.com/MarcelCoding/java-backend/actions/runs/2005466250
    * main: https://github.com/MarcelCoding/java-backend/actions/runs/2005436698

https://github.com/MarcelCoding/java-backend/blob/8c4bb556108a1034d66d58a49f545721b12784d7/.github/workflows/ci.yaml#L100-L115

### Logs

Flavors (build matrix):
[jvm.log](https://github.com/docker/metadata-action/files/8306503/jvm.log)
[native.log](https://github.com/docker/metadata-action/files/8306504/native.log)

**Comment by crazy-max** [comment]
If you want both semver and semver with suffix you have to dedup the semver entries and remove the suffix flavor:

```yaml
          tags: |
            type=edge
            type=semver,pattern={{version}},suffix=-${{ matrix.flavor }}
            type=semver,pattern={{major}}.{{minor}},suffix=-${{ matrix.flavor }}
            type=semver,pattern={{major}},suffix=-${{ matrix.flavor }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=edge,enable=${{ matrix.flavor == 'jvm' && endsWith(github.ref, github.event.repository.default_branch) }}
          flavor: |
            latest=${{ matrix.flavor == 'jvm' && 'auto' || 'false' }}
```

**Comment by MarcelCoding** [comment]
Thanks for your reply. This is getting kind of messy and there isn't event an enabled for the semver without suffix like for edge.

I think I am going to use my fork and don't switch to v3.
