### ISSUE TITLE
Typo in documentation example for semver

### ISSUE THREAD

**Issue by fduran** [docker/metadata-action#178]
In the example for semver in the documentation we have:

```
tags:
      - 'v*'
```

In "pure" simver "1.2.3" (vs basic example "v1.2.3") the action won't be triggered because of the leading `v`; it should be:

```
tags:
      - '*'
```

**Comment by crazy-max** [comment]
This is not a typo:

> A leading "=" or "v" character is stripped off and ignored.

See https://www.npmjs.com/package/semver#versions

**Comment by fduran** [comment]
The v character wasn’t striped in my repo or somehow it failed and when
taken out it worked.
