### ISSUE TITLE
Export bare tag names

### ISSUE THREAD

**Issue by penguineer** [docker/metadata-action#212]
For integration with other tools (such as [JIB](https://github.com/GoogleContainerTools/jib)) I would like access to  the bare tag names (without the image name prepended), so that I can use this action even when the image name is created by another tool and complete image names cannot be specified.

**Comment by ScottGuymer** [comment]
This option would also enable to use other actions such as https://github.com/mr-smithers-excellent/docker-build-push/

Which are needed if you want to use windows, as the docker action does not support windows containers https://github.com/docker/build-push-action/issues/18

**Comment by vanicekv** [comment]
Exactly as written, it would allow using other actions for Windows for example. Support with the package [https://github.com/mr-smithers-excellent/docker-build-push/](https://github.com/mr-smithers-excellent/docker-build-push/) would be more than helpful.

**Comment by hotrungnhan** [comment]
+1

**Comment by jasondamour** [comment]
@crazy-max Can you give any insight as to what the `inputs.image.enabled` variable is supposed to do? Seems to do nothing

**Comment by irux** [comment]
@jasondamour @crazy-max any updates on this ?

**Comment by penguineer** [comment]
Thank you for resolving this issue!
