### ISSUE TITLE
Request for additional documentation of `priority`

### ISSUE THREAD

**Issue by wholtz** [docker/metadata-action#224]
Thank you for providing a very useful action.

I would like to see additional documentation about the `priority` attribute.  The documentation that I can find on `priority` consists of:

`priority=<number>` priority to manage the order of tags

Some questions that could be clarified by additional documentation:
1. In what context does `priority` impact ordering of tags? On https://hub.docker.com/? On other container registries? On the API results returned from https://hub.docker.com/v2/?
1. Do smaller `priority` values result in being first or last in the resulting ordering?

**Comment by omBratteng** [comment]
I think some information in how priority affects the output of the action is needed.
Meanwhile I did some testing, with these settings:
```yaml
tags: |
  type=sha,priority=100
  type=raw,priority=150,value=medium-priority
  type=raw,priority=200,value=higher-priority
```

I noticed that it affects the tag set in the image version and the order of which the tags are output. This way you can control the image version if you want to output several tags.
```
Docker image version
  higher-priority
Docker tags
  image/name:higher-priority
  image/name:medium-priority
  image/name:sha-643a62d
Docker labels
  org.opencontainers.image.version=higher-priority
```

**Comment by crazy-max** [comment]
> I noticed that it affects the tag set in the image version and the order of which the tags are output.

Yes `priority` affects tags order so image version will be set for the higher one.
