### ISSUE TITLE
How to loop over JSON output of docker/metadata-action to push each tag?

### ISSUE THREAD

**Issue by semihural-tomtom** [docker/metadata-action#254]
I am using composite action with `docker/build-push-action@v3` and `docker/metadata-action@v4`.

How should I loop over the JSON output to get each tag in tags array?

Here is the output

```
JSON output
  {
    "tags": [
      "azurecr.io/internal/dx-integration-bootstrap:feature-docker-action-bootstrap",
      "azurecr.io/internal/dx-integration-bootstrap:sha-e3416c8"
    ],
    
```
I tried to do something like the below but it did not work, cause the tag returns Array. How should I achieve this?

    - name: Push Image
      if: ${{ inputs.registry }}
      run: |
        for tag in ${{ fromJSON(steps.meta.outputs.json).tags }}; do
          echo $tag
          docker buildx imagetools create --tag $tag
        done
      shell: bash

Result ->

    Run for tag in Array; do
      for tag in Array; do
        echo $tag
      done
      shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
    Array

**Comment by crazy-max** [comment]
You can do smth like:

```yaml
      -
        name: Iterate tags
        run: |
          for tag in $(jq -r '.tags[]' <<< "$DOCKER_METADATA_OUTPUT_JSON"); do
            echo $tag
          done
```

**Comment by danielorbach** [comment]
Specifically, for pushing to a registry I ran `docker push --all-tags <image name>` to push all the tags of the image.
