### ISSUE TITLE
label overwrite does not works as expected

### ISSUE THREAD

**Issue by sergey-safarov** [docker/metadata-action#289]
### Behaviour
In the action description, you can read
> If some [OCI Image Format Specification](https://github.com/opencontainers/image-spec/blob/master/annotations.md) labels generated are not suitable, you can overwrite them like this:
```
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: name/app
          labels: |
            maintainer=CrazyMax
            org.opencontainers.image.title=MyCustomTitle
            org.opencontainers.image.description=Another description
            org.opencontainers.image.vendor=MyCompany
```
[Link](https://github.com/docker/metadata-action#overwrite-labels)
I want to overwrite `org.opencontainers.image.source` and specified
```
       labels: |
          org.opencontainers.image.source=https://github.com/sergey-safarov/kamailio-ci
```
In the build log, I can see present two labels with the same key `org.opencontainers.image.source`
![image](https://user-images.githubusercontent.com/2562241/233740114-88eafdf6-d09b-4540-bdcf-474a9f7971f2.png)

#### Expected behaviour

Actions output should contain only one key/value pairs. And I am able to overwrite default keys.

#### Actual behaviour

The output contains multiple key/value pairs. Build actions take the first pair and I not able overwrite default values.

**Comment by crazy-max** [comment]
https://github.com/docker/metadata-action/issues/125#issuecomment-910761577

**Comment by sergey-safarov** [comment]
thanks @crazy-max, that will be optimal.
