### ISSUE TITLE
Proposol: add commit date variable

### ISSUE THREAD

**Issue by trim21** [docker/metadata-action#292]
like current `{{date '<format>' tz='<timezone>'}}`, use git commit date instead of current date, like `{{commit_date '<format>' tz='<timezone>'}}`

I can submit a PR if you are open to this feature.

**Comment by crazy-max** [comment]
Fine to have it, contrib welcomed thanks

**Comment by lvjp** [comment]
Resolved with #471  ?

**Comment by trim21** [comment]
yes
