### ISSUE TITLE
Context `git` fails

### ISSUE THREAD

**Issue by lucacome** [docker/metadata-action#293]
#### Steps to reproduce this issue

1. Checkout a tag
2. Use this action with `context: git`

#### Expected behaviour

The action gets the metadata from the commit of the tag

#### Actual behaviour

`Error: fatal: ref HEAD is not a symbolic ref`

### Configuration

* Repository URL (if public): https://github.com/nginxinc/kubernetes-ingress/blob/main/.github/workflows/build-oss.yml#L97
* Build URL (if public): https://github.com/nginxinc/kubernetes-ingress/actions/runs/5063685901/jobs/9090682543

### Logs

[logs_48538.zip](https://github.com/docker/metadata-action/files/11550199/logs_48538.zip)

**Comment by crazy-max** [comment]
Fixed by https://github.com/docker/metadata-action/pull/296

**Comment by lucacome** [comment]
Everything is working fine now, thanks @crazy-max !
