### ISSUE TITLE
latest tag README instructions cause errors

### ISSUE THREAD

**Issue by hozza** [docker/metadata-action#314]
#### Steps to reproduce this issue

1. Follow README for https://github.com/docker/metadata-action#latest-tag

#### Expected behaviour

> apply latest tag on a default main branch (not master)

#### Actual behaviour

> errors "buildx failed with: ERROR: invalid tag"... etc

### Configuration

From the README/docs

```
tags: |
  # set latest tag for master branch
  type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
```
```
tags: |
  # set latest tag for default branch
  type=raw,value=latest,enable={{is_default_branch}}
```

Both examples in the README are tried here and both fail the action: https://github.com/hozza/epiphyte/commit/fa2aa9b7d0aa437fc8bbef1406b5a8734dfe12f2

```
# set latest tag for default branch master/main bug https://github.com/docker/metadata-action#latest-tag
tags: |
  type=raw,value=latest,enable=${{ endsWith(github.ref, 'main') }}
```

Note: yes `${{ endsWith(github.ref, 'main') }}` is different here but that should not be relevant. 

Moving the comment out of the new line list fixed the issue: https://github.com/hozza/epiphyte/commit/6e017056ef85e6c53c477cbec6cdecf79f71fd03

### Conclusion

Should the README examples be updated - or better yet the latest tag should be auto added for `master` and the new default on Github `main`?

**Comment by crazy-max** [comment]
> `docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38`

You're using an old version of the metadata action, please update to latest stable.

**Comment by hozza** [comment]
Thanks @crazy-max! 

I used the template recommended by Github just earlier today. Is there a way to update what version Github suggests?

Does using the newest version solve the main vs master or the comment formatting issue?

**Comment by crazy-max** [comment]
Oh then the starter workflow is outdated https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml that's sad. I will raise a PR. Thanks for your input.

**Comment by crazy-max** [comment]
https://github.com/actions/starter-workflows/pull/2130
