### ISSUE TITLE
Custom annotations

### ISSUE THREAD

**Issue by favonia** [docker/metadata-action#360]
### Description

I hope there's a way to specify custom annotations in addition to the standard ones, just like the `labels` input. They are probably needed by ArtifactHub, and putting all the metadata configurations in one place looks more elegant.

One design decision to make is whether these custom annotations should be affected by `DOCKER_METADATA_ANNOTATIONS_LEVELS`. My personal preference is _yes,_ but I can see the arguments both ways.

**Comment by crazy-max** [comment]
Yes I think that makes, might have been an oversight when implementing #352
