### ISSUE TITLE
docker build fails if description contains rocker icon copied externally , if rocker icon is mentioned as ":rocket" it works fine.

### ISSUE THREAD

**Issue by vinaydevmd** [docker/metadata-action#462]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/metadata-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [ ] The documentation does not mention anything about my problem
- [ ] There are no open or closed issues that are related to my problem

### Description

Tried copying icon file directly into reop description and during my building docket build push actions fails because of icon file in repo description, if same thing is replaced with " :rocket" , build works perfectly fine.

Suggest us how to fix this issue from docket metada level or build and push level.

### Expected behaviour

metadata should recognize this icon file and replace with docker supported icon formats or ignore it during building.

### Actual behaviour

Its failing during docket build action with  failed commit on ref "manifest-

### YAML workflow

workflow is confidential

**Comment by crazy-max** [comment]
Please provide repro with link to workflow run and logs.
