### ISSUE TITLE
Latest not linked to the highest version

### ISSUE THREAD

**Issue by xezpeleta** [docker/metadata-action#80]
#### Steps to reproduce this issue

1. I configure the _metadata-action_ workflow in my repo with semantic version, as described[ in the instuctions](https://github.com/docker/metadata-action#semver)
2. I publish a new tag: **v2.0.1** - this will trigger the action and a new Docker image will be generated with the following tags: `2.0.1`, `2.0`, `2` and `latest`
3. Then I publish another tag: **v1.9.1** - this will trigger the action and a new Docker image will be generated with the following tags: `1.9.1`, `1.9`, `1` and `latest`

#### Expected behaviour

I want to have the "**_latest_**" tag always linked to the highest version (**v2.0.1**)

#### Actual behaviour

If I publish a revision of an older version (**v1.9.1**) it will overwrite the "**_latest_**" version.

Is this deliberate? Is there any workaround?

Thanks

**Comment by crazy-max** [comment]
@xezpeleta 

> Is this deliberate?

This is the expected behavior if you maintain multiple versions. And indeed, this is not really wise in your case.

> Is there any workaround?

You can tell the action to only create latest for `v2.x.x` tags will the following flavor:

```yaml
flavor: |
  latest=${{ startsWith(github.ref, 'refs/tags/v2.') }}
```

Btw can you post your workflow or do you have a link to your repo please?
