### ISSUE TITLE
[request] allow naming the tag output for type=edge

### ISSUE THREAD

**Issue by epsilon-0** [docker/metadata-action#84]
Currently I don't see a way for the `type=edge` to produce a custom docker tag.
Would it be possible to have this functionality?

Thanks a lot!

**Comment by crazy-max** [comment]
@epsilon-0 

> Currently I don't see a way for the `type=edge` to produce a custom docker tag.
> Would it be possible to have this functionality?

I think you want to create a custom tag if the event matches the default branch? If so then you can do smth like this:

```yaml
tags: |
  type=raw,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }},value=mytag
```

**Comment by epsilon-0** [comment]
great, thanks!
